config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  resources :categories, path: '/shop/categories'

  resources :reviews

  resources :orders

  resources :order_items, only: [:create, :destroy] do
    collection do
      delete :destroy_all
      put :update_all
    end
  end

  resource :cart, only: [:show]

  resources :books

  resources :authors

  resources :checkout

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :books
end

app/models/billing_address.rb
class BillingAddress < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_and_belongs_to_many :authors
  has_many :reviews, dependent: :delete_all
  belongs_to :category
  has_many :order_items
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :state
  belongs_to :coupon
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal_price
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.price) : 0 }.sum
  end

  def total_price
    !coupon.nil? && coupon.available ? self[:subtotal_price] * coupon.discount : self[:subtotal_price]
  end

  def update_total
    self[:total_price] = total_price
  end

  private
  def set_order_status
    self.state = State.find_by_name('in_progress')
  end

  def update_subtotal
    self[:subtotal_price] = subtotal_price
  end

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :book
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :book_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:price]
    else
      book.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def book_present
    if book.nil?
      errors.add(:book, 'is not valid or is not active.')
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, 'is not a valid order.')
    end
  end

  def finalize
    self[:price] = unit_price
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
end

app/models/shipping_address.rb
class ShippingAddress < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :orders
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find_by_id(params[:id])
    @order_item = current_order.order_items.new
    @description = @book.full_description
    @max_description_length = 2100
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
  def nav_bar
    content_tag(:ul, class: "nav navbar-nav") do
      yield
    end
  end

  def nav_link(*args)
    options = current_page?(args[1]) ? { class: "active" } : {}
    content_tag(:li, options) do
      link_to *args
    end
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_book_description.html.haml
%p.lead.book-description
  - if description.length > max_length
    = truncate description, length: max_length
    = link_to 'read more', 'javascript:void(0);', id: "read-more"
    :javascript
      $("#read-more").on('click', function(e) {
        e.preventDefault()
        $(this).parent().html('#{description}')
      })
  - else
    = description

app/views/books/_book_info.html.haml
- book ||= @book
- description ||= @description
- max_description_length ||= @max_description_length

.book-container{style: 'padding: 5px 10px 0px 100px;'}
  %h2.book-title
    - if @book
      = book.title
    - else
      = link_to book.title, book_path(book.id)
  by
  - authors = BooksService.new.authors_full_names(book.id)
  - authors.each_with_index do |name, index|
    = link_to name, "http://www.google.com/search?q=#{name.gsub(' ', '+')}", target: '_blank'
    = ',' unless index == authors.size - 1

  = image_tag book.image, class: 'book-image', style: 'float: left; padding-right: 50px; width: 300px; height: 400px;'

  = render('books/book_description', description: description, max_length: max_description_length)
  
  %h3.col-md-7{style: 'float: right;'}
    = form_for @order_item, class: 'form-inline' do |f|
      .col-md-2.price-text
        = f.label :price, '$'+book.price.to_s
      .col-md-3
        = f.number_field :quantity, {class: 'form-control bfh-number', value: '1', min: 1}
        = f.hidden_field :book_id, value: book.id
      .col-md-2
        = f.submit 'Add To Cart', class: 'btn btn-default'

app/views/books/_show.html.haml
- book = @book || book
.book-container{style: 'padding: 5px 10px 0px 100px;'}
  %h2.book-title
    - if @book
      = book.title
    - else
      = link_to book.title, book_path(book.id)
  by
  - authors = BooksService.new.authors_full_names(book.id)
  - authors.each_with_index do |name, index|
    = link_to name, "http://www.google.com/search?q=#{name.gsub(' ', '+')}", target: '_blank'
    = ',' unless index == authors.size - 1
  = image_tag book.image, class: 'book-image', style: 'float: left; padding-right: 50px;'
  %p.lead.book-short-description
    = book.full_description
  %h3.col-md-7{style: 'float: right;'}
    = form_tag new_order_item_path, class: 'form-inline' do
      .col-md-2.price-text
        = label_tag :price, '$'+book.price.to_s
      .col-md-3
        = number_field_tag :quantity, '1', {class: 'form-control bfh-number', min: 1}
      .col-md-2
        = submit_tag 'Add To Cart', class: 'btn btn-default'

app/views/books/show.html.haml
= render 'book_info'