config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  resources :categories, path: '/shop/categories'

  resources :reviews

  resources :orders

  resources :order_items, only: [:create, :destroy] do
    collection do
      delete :destroy_all
      put :update_all
    end
  end

  resource :cart, only: [:show]

  resources :books

  resources :authors

  resources :checkout

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :books
end

app/models/billing_address.rb
class BillingAddress < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_and_belongs_to_many :authors
  has_many :reviews, dependent: :delete_all
  belongs_to :category
  has_many :order_items
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :state
  belongs_to :coupon
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal_price
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.price) : 0 }.sum
  end

  def total_price
    !coupon.nil? && coupon.available ? self[:subtotal_price] * coupon.discount : self[:subtotal_price]
  end

  def update_total
    self[:total_price] = total_price
  end

  private
  def set_order_status
    self.state = State.find_by_name('in_progress')
  end

  def update_subtotal
    self[:subtotal_price] = subtotal_price
  end

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :book
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :book_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:price]
    else
      book.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def book_present
    if book.nil?
      errors.add(:book, 'is not valid or is not active.')
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, 'is not a valid order.')
    end
  end

  def finalize
    self[:price] = unit_price
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
end

app/models/shipping_address.rb
class ShippingAddress < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = current_order
    @order_items = @order.order_items
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
  def nav_bar
    content_tag(:ul, class: "nav navbar-nav") do
      yield
    end
  end

  def nav_link(*args)
    options = current_page?(args[1]) ? { class: "active" } : {}
    content_tag(:li, options) do
      link_to *args
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/carts/_cart_row.html.haml
.well{id: order_item.id, style: 'height: 190px; overflow: hidden;'}
  .row
    .col-xs-2
      = image_tag order_item.book.image, class: 'img-responsive', style: 'width: 100px; height: 150px;'
    .col-xs-6
      %h4
        = link_to order_item.book.title, book_path(order_item.book.id)
      %p.lead.book-short-description
        = truncate order_item.book.short_description, length: 360
    .col-xs-4
      .row
        .col-xs-4
          = f.number_field :quantity, value: order_item.quantity.to_i,
            id: "order-item-quantity-#{order_item.id}", class: 'form-control bfh-number', min: 1
        .col-xs-8.order-item-data
          .col-xs-4
            %h4.text-right
              %span.unit-price{style: 'color: green'}= number_to_currency(order_item.unit_price)
          .col-xs-4
            %h4.text-right
              %span.total-price{style: 'color: green'}= number_to_currency(order_item.total_price)
          .col-xs-4
            = link_to 'Delete', order_item, { data: { confirm: "Are you sure you wish to delete the book #{order_item.book.title} from your cart?" }, method: :delete, class: 'btn btn-danger' }

app/views/carts/_shopping_cart.html.haml
- if !@order_item.nil? && @order_item.errors.any?
  .alert.alert-danger
    %ul
      - @order_item.errors.full_messages.each do |msg|
        %li
          = msg
- if @order_items.size == 0
  %p.text-center
    There are no items in your shopping cart.  Please
    = link_to 'go back', root_path
    and add some items to your cart.
- else
  .row
    .col-xs-8
      %h4{style: 'text-align: center;'} Book
    .col-xs-4
      .col-xs-4
        %h4 QTY
      .col-xs-8
        .col-xs-4
          %h4{style: 'text-align: center;'} Unit price
        .col-xs-4
          %h4{style: 'text-align: center;'} Total price
  = form_tag update_all_order_items_path, method: :put do
    - @order_items.each do |order_item|
      = fields_for "order_items[]", order_item do |f|
        = render 'carts/cart_row', order_item: order_item, f: f
    .col-xs-12
      %h4{style: 'text-align: right;'}
        Subtotal:
        %span#subtotal-price
          = number_to_currency(@order.subtotal_price)
    .col-xs-12
      .col-xs-8
        = link_to 'Empty Cart', destroy_all_order_items_path, method: 'DELETE', class: 'btn btn-sm btn-default'
        = link_to 'Continue Shopping', categories_path, class: 'btn btn-sm btn-default'
        = submit_tag 'Update', class: 'btn btn-sm btn-default'
      .col-xs-4
        = text_field_tag :coupon, nil, placeholder: 'Coupon code'
        = link_to 'Checkout', checkout_index_path, class: 'btn btn-sm btn-primary'

app/views/carts/show.html.haml
.shopping-cart
  = render 'shopping_cart'