config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  resources :categories, path: '/shop/categories'

  resources :reviews

  resources :orders

  resources :order_items, only: [:create, :destroy] do
    collection do
      delete :destroy_all
      put :update_all
    end
  end

  resource :cart, only: [:show]

  resources :books

  resources :authors

  resources :checkout

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :books
end

app/models/billing_address.rb
class BillingAddress < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_and_belongs_to_many :authors
  has_many :reviews, dependent: :delete_all
  belongs_to :category
  has_many :order_items
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :state
  belongs_to :coupon
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal_price
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.price) : 0 }.sum
  end

  def total_price
    !coupon.nil? && coupon.available ? self[:subtotal_price] * coupon.discount : self[:subtotal_price]
  end

  def update_total
    self[:total_price] = total_price
  end

  private
  def set_order_status
    self.state = State.find_by_name('in_progress')
  end

  def update_subtotal
    self[:subtotal_price] = subtotal_price
  end

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :book
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :book_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:price]
    else
      book.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def book_present
    if book.nil?
      errors.add(:book, 'is not valid or is not active.')
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, 'is not a valid order.')
    end
  end

  def finalize
    self[:price] = unit_price
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
end

app/models/shipping_address.rb
class ShippingAddress < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :orders
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    @books = Book.all
  end

  def show
    @categories = Category.all
    @books = Category.find_by_id(params[:id]).books
    render 'categories/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
  def nav_bar
    content_tag(:ul, class: "nav navbar-nav") do
      yield
    end
  end

  def nav_link(*args)
    options = current_page?(args[1]) ? { class: "active" } : {}
    content_tag(:li, options) do
      link_to *args
    end
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/categories/_categories.html.haml
%p.lead
  Shop by categories
  .list-group
    %h4
      = 'There are no any categories' if @categories.empty?
    = link_to 'All', categories_path, class: 'list-group-item', style: 'text-align: center;'
    - @categories.each do |c|
      = link_to c.name, category_path(c.id), class: 'list-group-item', style: 'text-align: center;'

app/views/categories/index.html.haml
=link_to 'Home', root_path
>>
=link_to 'Shop', categories_path

.container
  .row
    .col-md-9
      .row
        %h2
          = 'There are no any books' if @books.empty?
        - @books.each do |book|
          .col-sm-4.col-lg-4.col-md-4
            .thumbnail
              = image_tag book.image, class: 'img-responsive', style: 'width: 200px; height: 300px;'
              .caption{style: 'height: 130px; overflow: hidden;'}
                %h4.pull-right
                  = book.price
                %h4
                  = link_to book.title, book_path(book.id), style: 'text-align: center;'
                %p
                  = truncate book.short_description, length: 120
    .col-md-3
      = render 'categories/categories'