config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  resources :categories, path: '/shop/categories'

  resources :reviews

  resources :orders

  resources :order_items, only: [:create, :destroy] do
    collection do
      delete :destroy_all
      put :update_all
    end
  end

  resource :cart, only: [:show]

  resources :books

  resources :authors

  resources :checkout

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :books
end

app/models/billing_address.rb
class BillingAddress < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_and_belongs_to_many :authors
  has_many :reviews, dependent: :delete_all
  belongs_to :category
  has_many :order_items
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :state
  belongs_to :coupon
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal_price
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.price) : 0 }.sum
  end

  def total_price
    !coupon.nil? && coupon.available ? self[:subtotal_price] * coupon.discount : self[:subtotal_price]
  end

  def update_total
    self[:total_price] = total_price
  end

  private
  def set_order_status
    self.state = State.find_by_name('in_progress')
  end

  def update_subtotal
    self[:subtotal_price] = subtotal_price
  end

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :book
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :book_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:price]
    else
      book.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def book_present
    if book.nil?
      errors.add(:book, 'is not valid or is not active.')
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, 'is not a valid order.')
    end
  end

  def finalize
    self[:price] = unit_price
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
end

app/models/shipping_address.rb
class ShippingAddress < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :orders
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
  def nav_bar
    content_tag(:ul, class: "nav navbar-nav") do
      yield
    end
  end

  def nav_link(*args)
    options = current_page?(args[1]) ? { class: "active" } : {}
    content_tag(:li, options) do
      link_to *args
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_cart_link.html.haml
= nav_link " Cart: #{current_order.order_items.size} ( #{number_to_currency(current_order.subtotal_price)} )", cart_path, class: 'cart-text'

app/views/layouts/_cart_text.html.haml
= nav_link " Cart: #{current_order.order_items.size} ( #{number_to_currency(current_order.subtotal_price)} )", cart_path, class: 'cart-text'

app/views/layouts/_header.html.haml
.navbar.navbar-default
  .container-fluid
    .navbar-header
      .navbar-brand
        The Bookstore
    .collapse.navbar-collapse
      = nav_bar do
        = nav_link 'HOME', root_path

        = nav_link 'SHOP', categories_path

        = render 'layouts/cart_link'

        = nav_link 'Settings', '#'

        = nav_link 'Orders', '#'

        = nav_link 'Sign out', '#'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Bookstore
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %link{href: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css', rel: 'stylesheet'}
    = csrf_meta_tags
  %body
    %div
      = render 'layouts/header'
    = yield